### ISSUE TITLE
Use case

### ISSUE THREAD

**Issue by phuwin1995** [FKK2015/SWED2015#1]
![swed usecase](https://cloud.githubusercontent.com/assets/8092739/7609493/a2078e6a-f973-11e4-8f9b-07c5d7f5089d.png)
created by Phu and Polish Kris

**Comment by K-Balabanov** [comment]
It has to be  in written form (I saw it mentioned at  least 2 times in the lectures slides). I will see if this will do or if it will have to be corrected.

**Comment by phuwin1995** [comment]
I will commit a written form version of the use case soon

**Comment by K-Balabanov** [comment]
I've done it already. Will send you my work this evening. It needs to be extended a bit.

**Comment by phuwin1995** [comment]
Hi, can you upload your work here? Did someone write a report?

**Comment by K-Balabanov** [comment]
Didnt have the time to elaborate. But we already have the template for the use cases and the diagram. We just have to add a bit to them. Last week a did a presentation so we are clear for this week and the next one. We only need 2-3-4 presentations about our project until the end of the term.

**Comment by K-Balabanov** [comment]
![liftsimulator](https://cloud.githubusercontent.com/assets/12345151/7766221/4fd45c72-0067-11e5-8a1c-af33b39fd830.jpg)

**Comment by K-Balabanov** [comment]
These are 3 of the use cases documented. It has to be done  like this , not
only with the diagram. Feelfree to think of more and  I will add them to
the document.

Regards,
Kris
