### ISSUE TITLE
Project/Team leader

### ISSUE THREAD

**Issue by K-Balabanov** [FKK2015/SWED2015#3]
I've described our team organization as democratic and open but with a team/project leader as a coordinator. It just looks better and is more effective if someone is supervising all of the work.
Now, I've assumed this position for now cause I've done it before and I had the Analysis lecture. But if anyone of you guys feels that he should be the team coordinator be my guest.

Let me know what you think about it.

**Comment by PastuszakKrzysztof** [comment]
Okey

**Comment by phuwin1995** [comment]
I agree with you.

**Comment by K-Balabanov** [comment]
Ok, closing this issue then :D
