### ISSUE TITLE
Use Case Diagram final

### ISSUE THREAD

**Issue by K-Balabanov** [FKK2015/SWED2015#5]
![liftsimulator](https://cloud.githubusercontent.com/assets/12345151/7901354/2899ceac-0784-11e5-975c-7f87e043e814.jpg)

Confirm if you approve :D

**Comment by PastuszakKrzysztof** [comment]
Are you sure that "Emergency" should be connected to controller ?

**Comment by K-Balabanov** [comment]
My idea was that the elevator has an automatic emergency option as well. If the ropes are disconnected the passenger will hardly have time to notice that the lift is falling down, whereas the sensors indicating the floor level will react immediately at the high speed.

**Comment by PastuszakKrzysztof** [comment]
If it is consistent with "Text Use Cases" and the rest of the project, I think we can leave it as it is.

**Comment by K-Balabanov** [comment]
I wrote "Important, good to be implemented, available in second increment". We are doing agile - a minimum of work :D

**Comment by PastuszakKrzysztof** [comment]
Sounds reasonable, so we stay with it
