### ISSUE TITLE
Activity Diagram reworked

### ISSUE THREAD

**Issue by K-Balabanov** [FKK2015/SWED2015#6]
![activitydiagram](https://cloud.githubusercontent.com/assets/12345151/7904137/3f1c412e-07f1-11e5-99ef-d023e0e06fe5.jpg)

Approve? :)

**Comment by PastuszakKrzysztof** [comment]
Emergency button should not be included in this diagram ?

**Comment by K-Balabanov** [comment]
It will just make it too complex since we have to add the emergency loop in several places. This emergency option is not in the requirements anyway, so I've written in the use cases that it will be implemented later.

**Comment by PastuszakKrzysztof** [comment]
OK, we can closed this issue
